version: '3.9'

services:
  kuma-api:
    build: ./kuma-api
    container_name: kuma-api
    restart: always
    env_file:
      - ".env"
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - app-network

  scheduler:
    build: ./scheduler
    container_name: scheduler
    restart: always
    env_file:
      - ".env"
    depends_on:
      - kuma-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
